### PR TITLE
Catched the errors from Umbraco.TypedContent

### PR DESCRIPTION
**Pull request by mzajkowski**
The description is inside the code (in comments).

### CODE REVIEW

**Comment by tomfulton** [comment]
@mzajkowski I came here today to look at this very issue - it was causing exceptions when a selected content page was unpublished.  Thanks! #h5yr ;)

**Comment by mzajkowski** [comment]
Yep, we've experienced the same problem @tomfulton. Glad that we found the issue :) It's also reported to Umbraco issues tracker here: http://issues.umbraco.org/issue/U4-9125. Please vote up!

**Comment by Jeavon** [comment]
Hmm, interesting, Umbraco shouldn't throw for unpublished content via TypedContent method!

**Comment by mzajkowski** [comment]
That's why we were so surprised when we discovered it. Especially that error message was related with membership provider.

**Pull request merged**
